# Занятие 7. Масштабирование, устойчивость и этика сбора — демонстрационный блокнот

**Курс:** Автоматизированный сбор данных из интернета (код + no-code)
**Формат:** демонстрация + база для лабораторной работы

> **Установка занятия.** Всё, что мы делаем в блокноте, служит одной цели — **не мешать сайту и не портить данные**: вежливая скорость, корректные повторы, условные запросы, диагностика отказов, наблюдаемость. Приёмы обхода средств защиты (решение капчи, подделка отпечатков, ротация IP для маскировки) обсуждаются как явление отрасли, но не применяются: они нарушают условия использования сайтов, а в ряде случаев — закон. Для демонстрации кодов ответа используется `httpbin.org` — сервис, специально созданный для тестирования HTTP-клиентов.

### Содержание + замечания по блокноту

| Блок | На что обратить внимание |
|---|---|
| 0. Подготовка и структурные логи | сессия, JSON-лог каждого запроса |
| 1. robots.txt | `can_fetch`, `Crawl-delay`, `Sitemap`, случай 404 |
| 2. Ограничение скорости | token bucket, джиттер, замер интервалов |
| 3. Адаптивная задержка | привязка скорости к латентности сервера |
| 4. Повторы и классификация ошибок | что повторять, backoff с джиттером, `Retry-After` |
| 5. Предохранитель | circuit breaker: closed → open → half-open |
| 6. Условные запросы | `ETag` → 304, экономия трафика, gzip |
| 7. Диагностика блокировки | маркеры заглушек, сравнение с историей |
| 8. Отчёт и оповещения | метрики прогона, пороги, вердикт |

⚠️ вопрос: «что правильно сделать, получив 429?» Обычный ответ студентов — «повторить». После блока 4 они должны формулировать иначе: 429 — это сообщение «сбавь скорость», а не техническое препятствие.

## 0. Подготовка: сессия и структурные логи

Каждый запрос пишется одной строкой JSON: время, домен, URL, код, длительность, попытка, идентификатор прогона. Это основа для всех метрик занятия — из текстовых логов агрегаты не посчитать.

In [ ]:
import json, math, os, random, statistics, time, uuid
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlparse
from urllib import robotparser

import pandas as pd
import requests

pd.set_option("display.width", 185)
pd.set_option("display.max_columns", 40)

WORK = Path("lecture7_demo").resolve()
WORK.mkdir(exist_ok=True)
os.chdir(WORK)

RUN_ID = uuid.uuid4().hex[:8]
LOG = WORK / "requests.log.jsonl"
LOG.unlink(missing_ok=True)

UA = "course-crawler/1.0 (+https://example.edu/crawler; educational use)"
session = requests.Session()
session.headers.update({"User-Agent": UA, "Accept-Encoding": "gzip, deflate"})

def log_event(**fields):
    """Одна строка = один JSON-объект. Никакого форматированного текста."""
    rec = {"ts": datetime.now(timezone.utc).isoformat(timespec="milliseconds"),
           "run_id": RUN_ID, **fields}
    with LOG.open("a", encoding="utf-8") as f:
        f.write(json.dumps(rec, ensure_ascii=False) + "\n")
    return rec

def fetch(url, attempt=1, timeout=15, **kw):
    """Запрос с протоколированием результата (в т.ч. сетевой ошибки)."""
    host = urlparse(url).netloc
    t0 = time.perf_counter()
    try:
        r = session.get(url, timeout=timeout, **kw)
    except requests.RequestException as e:
        log_event(event="request", host=host, url=url, status=None, attempt=attempt,
                  ms=round((time.perf_counter() - t0) * 1000), error=type(e).__name__)
        raise
    log_event(event="request", host=host, url=url, status=r.status_code, attempt=attempt,
              ms=round((time.perf_counter() - t0) * 1000), bytes=len(r.content),
              cached=r.status_code == 304)
    return r

print("Идентификатор прогона:", RUN_ID)
print("User-Agent:", UA)
print("Честный User-Agent с контактом даёт администратору возможность написать вам,")
print("а не блокировать вслепую. Это первый и самый дешёвый механизм вежливости.")

Идентификатор прогона: 478f1c13
User-Agent: course-crawler/1.0 (+https://example.edu/crawler; educational use)
Честный User-Agent с контактом даёт администратору возможность написать вам,
а не блокировать вслепую. Это первый и самый дешёвый механизм вежливости.

## 1. robots.txt: правила, задержка и карта сайта

`urllib.robotparser` читает файл и отвечает на три практических вопроса: можно ли забирать конкретный URL, какую задержку требует сайт, где карта сайта. Отдельно разбираем случай, когда файла нет (404): это **не** разрешение на любую нагрузку — условия использования продолжают действовать.

In [ ]:
def robots_report(base: str, probe_paths=("/",)):
    rp = robotparser.RobotFileParser()
    robots_url = base.rstrip("/") + "/robots.txt"
    raw = None
    try:
        r = session.get(robots_url, timeout=15)
        log_event(event="robots", url=robots_url, status=r.status_code)
        if r.status_code == 200:
            raw = r.text
            rp.parse(raw.splitlines())
        else:
            rp.parse([])                     # нет файла — явных правил нет
    except requests.RequestException as e:
        log_event(event="robots", url=robots_url, status=None, error=type(e).__name__)
        rp.parse([])
    return {
        "сайт": urlparse(base).netloc,
        "robots.txt": "есть" if raw else "нет (404)",
        "строк": len(raw.splitlines()) if raw else 0,
        "Crawl-delay для нас": rp.crawl_delay(UA),
        "request_rate": rp.request_rate(UA),
        "карт сайта": len(rp.site_maps() or []),
        **{f"can_fetch {p}": rp.can_fetch(UA, base.rstrip("/") + p) for p in probe_paths},
    }

rows = [
    robots_report("https://books.toscrape.com", ("/", "/catalogue/page-2.html")),
    robots_report("https://en.wikipedia.org", ("/wiki/Python", "/w/index.php?search=x")),
]
display(pd.DataFrame(rows).T)

print("Вывод для студентов:")
print("  • 404 на robots.txt ≠ «можно всё»: остаются условия использования и требование не мешать сайту;")
print("  • если Crawl-delay указан — это не рекомендация, а требование, и оно задаёт скорость сбора;")
print("  • Disallow на конкретных путях (например, поиск) чаще всего защищает сайт от дорогих запросов.")

                                                   0                 1
сайт                              books.toscrape.com  en.wikipedia.org
robots.txt                                 нет (404)              есть
строк                                              0               712
Crawl-delay для нас                             None              None
request_rate                                    None              None
карт сайта                                         0                 1
can_fetch /                                     True               NaN
can_fetch /catalogue/page-2.html                True               NaN
can_fetch /wiki/Python                           NaN              True
can_fetch /w/index.php?search=x                  NaN             False

Вывод для студентов:
  • 404 на robots.txt ≠ «можно всё»: остаются условия использования и требование не мешать сайту;
  • если Crawl-delay указан — это не рекомендация, а требование, и оно задаёт скорость сбора;
  • Disallow на конкретных путях (например, поиск) чаще всего защищает сайт от дорогих запросов.

In [ ]:
# Карта сайта дешевле полного обхода: список URL с датами изменения
sm_url = "https://en.wikipedia.org/robots.txt"
rp = robotparser.RobotFileParser()
rp.parse(session.get(sm_url, timeout=15).text.splitlines())
print("Карты сайта, объявленные в robots.txt:", rp.site_maps())
print()
print("Почему это важно: sitemap содержит lastmod, поэтому можно забирать только изменившееся.")
print("Полный обход 50 000 страниц ради 30 изменившихся — типичная ошибка масштабирования.")

Карты сайта, объявленные в robots.txt: ['https://en.wikipedia.org/w/rest.php/site/v1/sitemap/0']

Почему это важно: sitemap содержит lastmod, поэтому можно забирать только изменившееся.
Полный обход 50 000 страниц ради 30 изменившихся — типичная ошибка масштабирования.

## 2. Ограничение скорости: token bucket и джиттер

Ведро токенов наполняется с заданной скоростью, каждый запрос забирает токен: короткие всплески допустимы, средняя скорость держится. Джиттер убирает «машинную» ровность интервалов, которая сама по себе является признаком бота.

In [ ]:
class RateLimiter:
    """Token bucket: `rate` запросов в секунду, всплеск до `burst` запросов."""

    def __init__(self, rate: float, burst: int = 1, jitter: float = 0.25):
        self.rate, self.burst, self.jitter = rate, burst, jitter
        self.tokens = float(burst)
        self.updated = time.monotonic()

    def acquire(self):
        while True:
            now = time.monotonic()
            self.tokens = min(self.burst, self.tokens + (now - self.updated) * self.rate)
            self.updated = now
            if self.tokens >= 1:
                self.tokens -= 1
                if self.jitter:                       # ±jitter к интервалу
                    time.sleep(random.uniform(0, self.jitter / self.rate))
                return
            time.sleep((1 - self.tokens) / self.rate)

limiter = RateLimiter(rate=2, burst=2, jitter=0.3)
marks = []
for i in range(7):
    limiter.acquire()
    fetch("https://books.toscrape.com/")
    marks.append(time.monotonic())

gaps = [round(b - a, 2) for a, b in zip(marks, marks[1:])]
steady = gaps[1:]                    # без первого интервала: он относится к всплеску
print("Интервалы между запросами, с:", gaps)
print(f"Первый интервал {gaps[0]:.2f} c — это разрешённый всплеск (burst=2).")
print(f"Установившийся режим: средний интервал {statistics.mean(steady):.2f} c → "
      f"{1 / statistics.mean(steady):.2f} запр/с при лимите 2 запр/с.")
print("Интервалы неодинаковы из-за джиттера: ровный «машинный» профиль нагрузки сам по себе")
print("является признаком бота, поэтому 20–30% случайного разброса — часть вежливости.")

Интервалы между запросами, с: [0.15, 0.27, 0.5, 0.44, 0.61, 0.44]
Первый интервал 0.15 c — это разрешённый всплеск (burst=2).
Установившийся режим: средний интервал 0.45 c → 2.21 запр/с при лимите 2 запр/с.
Интервалы неодинаковы из-за джиттера: ровный «машинный» профиль нагрузки сам по себе
является признаком бота, поэтому 20–30% случайного разброса — часть вежливости.

**Что подчеркнуть.** Локальный лимит перестаёт работать при нескольких воркерах: два процесса с лимитом 2 запр/с дают сайту 4 запр/с. В распределённом сборе нужен общий счётчик (Redis), единая очередь с ограничением потребителей либо правило «один воркер на домен».

## 3. Адаптивная задержка: скорость по латентности сервера

Логика AutoThrottle из Scrapy (занятие 5), реализованная вручную: задержка ≈ измеренная латентность / целевая параллельность. Если сайт отвечает медленнее — сборщик сам отступает.

In [ ]:
class AdaptiveThrottle:
    """Задержка подстраивается под время ответа сервера."""

    def __init__(self, target_concurrency=1.0, start_delay=0.5, min_delay=0.2, max_delay=10.0):
        self.target = target_concurrency
        self.delay = start_delay
        self.min_delay, self.max_delay = min_delay, max_delay

    def observe(self, latency: float, status: int):
        target = latency / self.target
        self.delay = (self.delay + target) / 2                 # сглаживание
        if status in (429, 503):                               # сервер просит отступить
            self.delay = min(self.max_delay, max(self.delay * 2, 1.0))
        self.delay = min(self.max_delay, max(self.min_delay, self.delay))
        return self.delay

throttle = AdaptiveThrottle(target_concurrency=1.0)
rows = []
for url in ["https://books.toscrape.com/",
            "https://books.toscrape.com/catalogue/page-2.html",
            "https://en.wikipedia.org/wiki/Web_scraping",
            "https://books.toscrape.com/catalogue/page-3.html"]:
    t0 = time.perf_counter()
    r = fetch(url)
    lat = time.perf_counter() - t0
    delay = throttle.observe(lat, r.status_code)
    rows.append({"домен": urlparse(url).netloc, "латентность, мс": round(lat * 1000),
                 "код": r.status_code, "новая задержка, с": round(delay, 2)})
    time.sleep(delay)

display(pd.DataFrame(rows))
print("Медленный сервер автоматически получает более редкие запросы — без ручной подстройки.")
print("Ответ 429 или 503 удваивает задержку: это встроенная реакция на просьбу сбавить скорость.")

                домен  латентность, мс  код  новая задержка, с
0  books.toscrape.com               16  200               0.26
1  books.toscrape.com               17  200               0.20
2    en.wikipedia.org                6  200               0.20
3  books.toscrape.com               17  200               0.20

Медленный сервер автоматически получает более редкие запросы — без ручной подстройки.
Ответ 429 или 503 удваивает задержку: это встроенная реакция на просьбу сбавить скорость.

## 4. Повторы: что повторять и как ждать

Классификация ошибок — основа политики. Повторять имеет смысл только временные сбои; 4xx (кроме 429) повторять бессмысленно и вредно.

In [ ]:
def classify(status, exc=None):
    if exc is not None:
        return "временная сетевая ошибка", True
    if 200 <= status < 300:
        return "успех", False
    if status == 304:
        return "не изменилось (кэш)", False
    if status == 429:
        return "ограничение скорости", True
    if status in (500, 502, 503, 504):
        return "сбой сервера", True
    if status in (401, 403):
        return "нет доступа / возможная блокировка", False
    if 400 <= status < 500:
        return "ошибка клиента", False
    return "прочее", False

table = [{"код/ситуация": k, "класс": classify(k)[0], "повторять": "да" if classify(k)[1] else "нет"}
         for k in (200, 304, 400, 401, 403, 404, 422, 429, 500, 503)]
table.append({"код/ситуация": "таймаут/разрыв", "класс": "временная сетевая ошибка", "повторять": "да"})
display(pd.DataFrame(table))

      код/ситуация                               класс повторять
0              200                               успех       нет
1              304                 не изменилось (кэш)       нет
2              400                      ошибка клиента       нет
3              401  нет доступа / возможная блокировка       нет
4              403  нет доступа / возможная блокировка       нет
5              404                      ошибка клиента       нет
6              422                      ошибка клиента       нет
7              429                ограничение скорости        да
8              500                        сбой сервера        да
9              503                        сбой сервера        да
10  таймаут/разрыв            временная сетевая ошибка        да

In [ ]:
def backoff_delay(attempt, base=0.5, cap=20.0, mode="full_jitter"):
    raw = min(cap, base * 2 ** attempt)
    if mode == "full_jitter":
        return random.uniform(0, raw)          # рекомендуемый вариант
    if mode == "equal_jitter":
        return raw / 2 + random.uniform(0, raw / 2)
    return raw                                  # без джиттера

demo = pd.DataFrame({
    "попытка": range(6),
    "без джиттера": [round(backoff_delay(n, mode="none"), 2) for n in range(6)],
    "full jitter": [round(backoff_delay(n), 2) for n in range(6)],
    "equal jitter": [round(backoff_delay(n, mode="equal_jitter"), 2) for n in range(6)],
})
display(demo)
print("Без джиттера тысяча клиентов повторяет синхронно и снова роняет восстанавливающийся сервис.")

   попытка  без джиттера  full jitter  equal jitter
0        0           0.5         0.26          0.31
1        1           1.0         0.96          0.71
2        2           2.0         0.31          1.25
3        3           4.0         3.25          3.39
4        4           8.0         2.53          5.35
5        5          16.0        11.73         10.68

Без джиттера тысяча клиентов повторяет синхронно и снова роняет восстанавливающийся сервис.

In [ ]:
def get_with_retry(url, attempts=4, base=0.4, cap=6.0, limiter=None, throttle=None):
    """Повторы только для временных ошибок; уважаем Retry-After; ждём с джиттером."""
    history = []
    for n in range(attempts):
        if limiter:
            limiter.acquire()
        try:
            r = fetch(url, attempt=n + 1)
            cls, retryable = classify(r.status_code)
        except requests.RequestException as e:
            cls, retryable, r = classify(None, e), True, None
            cls = cls[0] if isinstance(cls, tuple) else cls
        if r is not None and not retryable:
            history.append({"попытка": n + 1, "код": r.status_code, "класс": cls, "ждём, с": 0})
            return r, pd.DataFrame(history)
        wait = 0.0
        if retryable:
            ra = (r.headers.get("Retry-After") if r is not None else None)
            wait = float(ra) if (ra and ra.isdigit()) else backoff_delay(n, base, cap)
            wait = min(wait, 3.0)              # на лекции ограничиваем ожидание
        history.append({"попытка": n + 1, "код": None if r is None else r.status_code,
                        "класс": cls, "источник задержки": "Retry-After" if (r is not None and r.headers.get("Retry-After")) else "backoff",
                        "ждём, с": round(wait, 2)})
        time.sleep(wait)
    return None, pd.DataFrame(history)

print("A. Сбой сервера (503) — повторяем с растущей задержкой:")
r, hist = get_with_retry("https://httpbin.org/status/503", attempts=4)
display(hist)

print("B. Ошибка клиента (404) — повтор бессмыслен, выходим сразу:")
r, hist = get_with_retry("https://httpbin.org/status/404", attempts=4)
display(hist)

print("C. Сервер явно указал Retry-After — ждём столько, сколько просят:")
resp = fetch("https://httpbin.org/response-headers?Retry-After=2")
print("   заголовок Retry-After в ответе:", resp.headers.get("Retry-After"),
      "— именно это значение имеет приоритет над нашим backoff.")

A. Сбой сервера (503) — повторяем с растущей задержкой:

   попытка  код         класс источник задержки  ждём, с
0        1  503  сбой сервера           backoff     0.06
1        2  503  сбой сервера           backoff     0.24
2        3  503  сбой сервера           backoff     1.15
3        4  503  сбой сервера           backoff     1.78

B. Ошибка клиента (404) — повтор бессмыслен, выходим сразу:

   попытка  код           класс  ждём, с
0        1  404  ошибка клиента        0

C. Сервер явно указал Retry-After — ждём столько, сколько просят:
   заголовок Retry-After в ответе: 2 — именно это значение имеет приоритет над нашим backoff.

## 5. Предохранитель (Патерн circuit breaker)

При устойчивом отказе домена бессмысленно и невежливо продолжать стучаться. Предохранитель переводит домен в состояние `open`: запросы не отправляются заданное время, затем делается один пробный запрос (`half-open`).

In [ ]:
class CircuitBreaker:
    def __init__(self, fail_threshold=3, reset_after=5.0):
        self.fail_threshold, self.reset_after = fail_threshold, reset_after
        self.state, self.failures, self.opened_at = "closed", 0, 0.0

    def allow(self) -> bool:
        if self.state == "open":
            if time.monotonic() - self.opened_at >= self.reset_after:
                self.state = "half-open"
                return True
            return False
        return True

    def record(self, ok: bool):
        if ok:
            self.state, self.failures = "closed", 0
        else:
            self.failures += 1
            if self.state == "half-open" or self.failures >= self.fail_threshold:
                self.state, self.opened_at = "open", time.monotonic()

cb = CircuitBreaker(fail_threshold=3, reset_after=4.0)
timeline = []
for i in range(9):
    if not cb.allow():
        timeline.append({"шаг": i + 1, "состояние": cb.state, "запрос": "пропущен",
                         "код": "—", "комментарий": "домен на паузе, сайт не нагружаем"})
        log_event(event="circuit", host="httpbin.org", state=cb.state, skipped=True)
        time.sleep(1)
        continue
    url = "https://httpbin.org/status/503" if i < 6 else "https://httpbin.org/status/200"
    try:
        r = fetch(url, attempt=i + 1)
        ok = r.status_code < 500
        codeval = r.status_code
    except requests.RequestException:
        ok, codeval = False, None
    state_before = cb.state
    cb.record(ok)
    timeline.append({"шаг": i + 1, "состояние": state_before, "запрос": "отправлен",
                     "код": codeval, "комментарий": f"→ {cb.state}"})
    time.sleep(0.4)

display(pd.DataFrame(timeline))
print("Смысл: пайплайн деградирует предсказуемо — проблемный источник помечается недоступным,")
print("остальные продолжают собираться, а сайт не получает шторм повторов.")

   шаг  состояние     запрос  код                        комментарий
0    1     closed  отправлен  503                           → closed
1    2     closed  отправлен  503                           → closed
2    3     closed  отправлен  503                             → open
3    4       open   пропущен    —  домен на паузе, сайт не нагружаем
4    5       open   пропущен    —  домен на паузе, сайт не нагружаем
5    6       open   пропущен    —  домен на паузе, сайт не нагружаем
6    7       open   пропущен    —  домен на паузе, сайт не нагружаем
7    8  half-open  отправлен  200                           → closed
8    9     closed  отправлен  200                           → closed

Смысл: пайплайн деградирует предсказуемо — проблемный источник помечается недоступным,
остальные продолжают собираться, а сайт не получает шторм повторов.

## 6. Условные запросы: самый недооценённый механизм вежливости

`ETag` + `If-None-Match` (или `Last-Modified` + `If-Modified-Since`) дают ответ **304 Not Modified** без тела: трафик почти нулевой, сервер почти не нагружается, а сборщик сразу понимает, что данные не изменились.

In [ ]:
ETAG_URL = "https://httpbin.org/etag/course-demo-v1"

first = fetch(ETAG_URL)
etag = first.headers.get("ETag")
print(f"Первый запрос : {first.status_code}, тело {len(first.content)} байт, ETag={etag}")

second = fetch(ETAG_URL, headers={"If-None-Match": etag})
print(f"Повторный     : {second.status_code}, тело {len(second.content)} байт "
      f"({'данные не изменились' if second.status_code == 304 else 'данные обновились'})")

saved = len(first.content) - len(second.content)
print(f"Сэкономлено на одном запросе: {saved} байт; при 50 000 страницах в сутки это "
      f"{saved * 50_000 / 1_048_576:.1f} МБ и соответствующая нагрузка, которую сайт не получит.")

# gzip: второй бесплатный способ сократить трафик
plain = requests.get("https://books.toscrape.com/", timeout=15,
                     headers={"User-Agent": UA, "Accept-Encoding": "identity"})
gz = session.get("https://books.toscrape.com/", timeout=15)
display(pd.DataFrame([
    {"режим": "без сжатия", "передано, байт": len(plain.content),
     "Content-Encoding": plain.headers.get("Content-Encoding", "—")},
    {"режим": "gzip", "передано, байт": int(gz.headers.get("Content-Length", len(gz.content))),
     "Content-Encoding": gz.headers.get("Content-Encoding", "—")},
]))

Первый запрос : 200, тело 367 байт, ETag=course-demo-v1
Повторный     : 304, тело 0 байт (данные не изменились)
Сэкономлено на одном запросе: 367 байт; при 50 000 страницах в сутки это 17.5 МБ и соответствующая нагрузка, которую сайт не получит.

        режим  передано, байт Content-Encoding
0  без сжатия           51294                —
1        gzip           51294                —

**Практическая связка с занятиями 3 и 6:** `ETag`/`Last-Modified` хранятся вместе с записью (в служебных полях слоя raw), и при следующем прогоне отправляются обратно. В сочетании с «водяным знаком» и sitemap это превращает ежедневный полный обход в короткий инкрементальный.

## 7. Диагностика блокировки: тихий отказ опаснее явного

Худший сценарий — код `200`, но в теле заглушка, проверка «вы человек?» или пустой список. Пайплайн продолжает работать и записывает мусор. Поэтому проверяем не только код, но и содержимое, и сравниваем объём с историей прогонов.

In [ ]:
BLOCK_MARKERS = ["captcha", "are you human", "access denied", "unusual traffic",
                 "доступ ограничен", "подтвердите, что вы не робот", "cf-browser-verification",
                 "request blocked", "rate limit exceeded"]

def inspect_response(resp, expected_selector_count=None, min_bytes=2000):
    """Возвращает вердикт: ok / подозрение / блокировка."""
    body = resp.text.lower()
    found = [m for m in BLOCK_MARKERS if m in body]
    signals = []
    if resp.status_code in (403, 429):
        signals.append(f"код {resp.status_code}")
    if found:
        signals.append("маркеры: " + ", ".join(found[:3]))
    if len(resp.content) < min_bytes:
        signals.append(f"подозрительно маленький ответ ({len(resp.content)} байт)")
    if expected_selector_count is not None and expected_selector_count == 0:
        signals.append("нет ожидаемых элементов при коде 200")
    verdict = "блокировка" if (found or resp.status_code in (403, 429)) else (
        "подозрение" if signals else "ok")
    return verdict, signals

from bs4 import BeautifulSoup

real = fetch("https://books.toscrape.com/")
n_cards = len(BeautifulSoup(real.text, "html.parser").select("article.product_pod"))
v1 = inspect_response(real, expected_selector_count=n_cards)

fake_html = "<html><body><h1>Access denied</h1><p>Please complete the CAPTCHA to continue.</p></body></html>"
class FakeResp:                       # имитация «вежливой» заглушки с кодом 200
    status_code, text = 200, fake_html
    content = fake_html.encode()
    headers = {}
v2 = inspect_response(FakeResp(), expected_selector_count=0)

display(pd.DataFrame([
    {"ответ": "реальная страница каталога", "код": real.status_code, "байт": len(real.content),
     "карточек": n_cards, "вердикт": v1[0], "сигналы": "; ".join(v1[1]) or "—"},
    {"ответ": "заглушка с кодом 200", "код": 200, "байт": len(FakeResp.content),
     "карточек": 0, "вердикт": v2[0], "сигналы": "; ".join(v2[1])},
]))
print("Реакция на вердикт «блокировка»: остановить домен, снять артефакты, снизить скорость,")
print("сообщить ответственному. Не увеличивать частоту и не обходить защиту.")

                        ответ  код   байт  карточек     вердикт                                            сигналы
0  реальная страница каталога  200  51294        20          ok                                                  —
1        заглушка с кодом 200  200     95         0  блокировка  маркеры: captcha, access denied; подозрительно...

Реакция на вердикт «блокировка»: остановить домен, снять артефакты, снизить скорость,
сообщить ответственному. Не увеличивать частоту и не обходить защиту.

In [ ]:
# Сравнение с историей прогонов: ловим «тихую» деградацию сбора
history = pd.DataFrame([
    {"прогон": "2026-09-18", "записей": 1000, "avg_bytes": 51_000, "err_rate": 0.01},
    {"прогон": "2026-09-19", "записей": 998, "avg_bytes": 50_800, "err_rate": 0.01},
    {"прогон": "2026-09-20", "записей": 1005, "avg_bytes": 51_200, "err_rate": 0.02},
    {"прогон": "2026-09-21", "записей": 640, "avg_bytes": 12_400, "err_rate": 0.11},   # инцидент
])
med_items = history["записей"].iloc[:-1].median()
med_bytes = history["avg_bytes"].iloc[:-1].median()
last = history.iloc[-1]

checks = pd.DataFrame([
    {"проверка": "объём данных к медиане", "значение": f"{last['записей'] / med_items:.0%}",
     "порог": "≥ 80%", "статус": "КРАСНЫЙ" if last["записей"] < 0.8 * med_items else "ок"},
    {"проверка": "средний размер ответа", "значение": f"{last['avg_bytes'] / med_bytes:.0%}",
     "порог": "≥ 70%", "статус": "КРАСНЫЙ" if last["avg_bytes"] < 0.7 * med_bytes else "ок"},
    {"проверка": "доля ошибок", "значение": f"{last['err_rate']:.0%}",
     "порог": "≤ 5%", "статус": "КРАСНЫЙ" if last["err_rate"] > 0.05 else "ок"},
])
display(history)
display(checks)
print("Такой контроль обнаруживает поломку селекторов и мягкую блокировку в день инцидента,")
print("а не через две недели по жалобе заказчика на «странные» отчёты.")

       прогон  записей  avg_bytes  err_rate
0  2026-09-18     1000      51000      0.01
1  2026-09-19      998      50800      0.01
2  2026-09-20     1005      51200      0.02
3  2026-09-21      640      12400      0.11

                 проверка значение  порог   статус
0  объём данных к медиане      64%  ≥ 80%  КРАСНЫЙ
1   средний размер ответа      24%  ≥ 70%  КРАСНЫЙ
2             доля ошибок      11%   ≤ 5%  КРАСНЫЙ

Такой контроль обнаруживает поломку селекторов и мягкую блокировку в день инцидента,
а не через две недели по жалобе заказчика на «странные» отчёты.

## 8. Отчёт о прогоне из структурных логов

Все запросы занятия уже записаны в `requests.log.jsonl`. Считаем метрики прогона и применяем пороги оповещения — это и есть минимальная наблюдаемость пайплайна.

In [ ]:
logs = pd.read_json(LOG, lines=True)
reqs = logs[logs["event"] == "request"].copy()

by_status = (reqs["status"].fillna(-1).astype(int).value_counts()
             .rename_axis("код").reset_index(name="запросов")
             .replace({"код": {-1: "сетевая ошибка"}}))
display(by_status)

lat = reqs["ms"].dropna()
metrics = {
    "запросов всего": len(reqs),
    "доменов": reqs["host"].nunique(),
    "доля ошибок, %": round(float((reqs["status"].isna() | (reqs["status"] >= 400)).mean() * 100), 1),
    "доля 429/403, %": round(float(reqs["status"].isin([403, 429]).mean() * 100), 1),
    "латентность медиана, мс": int(lat.median()),
    "латентность p95, мс": int(lat.quantile(0.95)),
    "трафик, КБ": round(float(reqs["bytes"].fillna(0).sum() / 1024), 1),
    "ответов 304 (кэш), шт": int((reqs["status"] == 304).sum()),
    "повторных попыток, шт": int((reqs["attempt"] > 1).sum()),
    "активаций предохранителя": int((logs.get("skipped") == True).sum()) if "skipped" in logs else 0,
}
THRESHOLDS = {"доля ошибок, %": 5, "доля 429/403, %": 0.001, "латентность p95, мс": 5000}
rows = []
for k, v in metrics.items():
    limit = THRESHOLDS.get(k)
    status = "—" if limit is None else ("ВНИМАНИЕ" if v > limit else "ок")
    rows.append({"метрика": k, "значение": v, "порог": limit if limit is not None else "—",
                 "статус": status})
report = pd.DataFrame(rows)
display(report)

alerts = report[report["статус"] == "ВНИМАНИЕ"]["метрика"].tolist()
print("Оповещения по прогону:", ", ".join(alerts) if alerts else "нет")
print("\nЗамечание для занятия: доля ошибок здесь высокая намеренно — мы специально запрашивали")
print("503 и 404 у httpbin. В реальном прогоне такой отчёт означал бы немедленное разбирательство.")

   код  запросов
0  200        16
1  503         7
2  404         1
3  304         1

                    метрика  значение  порог    статус
0            запросов всего      25.0      —         —
1                   доменов       3.0      —         —
2            доля ошибок, %      32.0      5  ВНИМАНИЕ
3           доля 429/403, %       0.0  0.001        ок
4   латентность медиана, мс      17.0      —         —
5       латентность p95, мс     368.0   5000        ок
6                трафик, КБ     781.5      —         —
7     ответов 304 (кэш), шт       1.0      —         —
8     повторных попыток, шт       7.0      —         —
9  активаций предохранителя       4.0      —         —

Оповещения по прогону: доля ошибок, %

Замечание для занятия: доля ошибок здесь высокая намеренно — мы специально запрашивали
503 и 404 у httpbin. В реальном прогоне такой отчёт означал бы немедленное разбирательство.

## 9. Прокси и ротация: только конфигурация, без применения

Показываем, **как** это настраивается технически — и сразу фиксируем правовую рамку. В работах курса прокси не используются.

```python
# Формально прокси задаётся одним параметром:
proxies = {"http": "http://user:pass@proxy.example:3128",
           "https": "http://user:pass@proxy.example:3128"}
# session.get(url, proxies=proxies, timeout=15)
```

| Сценарий | Оценка |
|---|---|
| Свои адреса для географически распределённого мониторинга доступности | как правило, допустимо |
| Корпоративный прокси как единственный выход в интернет | нейтрально, инфраструктурная необходимость |
| Пул адресов, чтобы сайт не заметил массовый сбор | обход защиты: нарушение ToS, риски |
| Ротация IP после наложенной блокировки | выраженный отказ в доступе обходится намеренно — худшая позиция |
| Автоматическое решение капчи | обход технического средства защиты |

**Что делать вместо обхода:** искать официальный API; запросить доступ письмом (для исследовательских задач это часто срабатывает); снизить скорость и объём; использовать открытые датасеты ([Common Crawl](https://commoncrawl.org/), порталы открытых данных, [Wikidata](https://www.wikidata.org/)); зафиксировать в документации проекта, что источник легально недоступен, и исключить его из пайплайна.

## 10. Устойчивость в no-code: что встроено и чего это стоит

| Механизм | Код (Python / Scrapy) | Octoparse | n8n |
|---|---|---|---|
| Ограничение скорости | token bucket, `DOWNLOAD_DELAY`, AutoThrottle | задержки и таймауты AJAX в шагах задачи | узел `Wait`, размер батча в `Loop Over Items` |
| Повторы | `Retry`/backoff, `RETRY_TIMES` | повторы шага, облачное исполнение | Retry On Fail: число попыток и интервал |
| Предохранитель | свой circuit breaker | нет явного аналога | `Stop And Error` + ветка ошибки, ограничение выполнений |
| Условные запросы / кэш | `ETag`, `HTTPCACHE_ENABLED` | нет прямого управления | вручную через заголовки в `HTTP Request` |
| Ротация IP, капча, JS | реализуется самостоятельно (в курсе не применяется) | встроено в облачных планах | делегируется скрапинг-API |
| Логи и история | структурные JSON-логи, статистика Scrapy | журнал задач в интерфейсе | журнал выполнений по узлам |
| Оповещения | свой код | уведомления о завершении/сбое | `Error Trigger` → Telegram / Email / Slack |
| Расписание | cron, Scrapyd | облачное расписание | `Schedule Trigger` |

**Два вывода, которые должны остаться после занятия:**

1. **Правовая ответственность не делегируется.** «Инструмент сам решил капчу» — не аргумент: заказчик сбора отвечает за то, как получены данные.
2. **Встроенная устойчивость стоит денег.** Облачные запуски, ротация IP и JS-рендеринг тарифицируются по запросам; при росте объёма стоимость растёт быстрее, чем у собственной инфраструктуры. Поэтому первым шагом всегда остаётся сокращение числа запросов: API, sitemap, условные запросы, инкрементальность.

**Вопрос для обсуждения (3 мин):** пайплайн начал получать 429 после увеличения объёма сбора в 5 раз. Заказчик просит «добавить прокси, чтобы не блокировали». Что вы предложите? Ожидаемый разбор: сначала выяснить, нужен ли весь объём (sitemap, инкрементальность, условные запросы); снизить скорость и включить адаптивную задержку; проверить наличие API и лимитов в документации; связаться с владельцем сайта; и только в правомерных сценариях обсуждать инфраструктуру. Ротация IP как способ «не быть замеченным» — это перевод технической проблемы в правовую.

## Итоги и переход к лабораторной работе

Что студент должен унести с занятия:

1. `429` — сообщение «сбавь скорость»; реакция — снижение темпа, а не учащение попыток.
2. Token bucket с джиттером и лимит на домен; понимание, что локальный лимит не работает в распределённом сборе.
3. Адаптивная задержка по латентности сервера.
4. Классификация ошибок и политика повторов: backoff с джиттером, приоритет `Retry-After`, лимит попыток.
5. Circuit breaker как способ предсказуемой деградации.
6. `robots.txt` (`can_fetch`, `Crawl-delay`, `Sitemap`), условные запросы и gzip как основные средства снижения нагрузки.
7. Детектор блокировки по маркерам и сравнение с историей прогонов — против «тихой» порчи данных.
8. Структурные логи → метрики прогона → пороги оповещения.
9. Правовая рамка: ToS, обход защиты, персональные данные, невозможность делегировать ответственность инструменту.

**Лабораторная работа (6 часов):** превратить один из ранее написанных сборщиков в устойчивый пайплайн с ограничением скорости, политикой повторов, предохранителем, условными запросами, детектором блокировки, структурными логами и отчётом о прогоне; повторить устойчивость в no-code и подготовить правовой чек-лист. Полное условие — в отдельном файле задания.

### Типичные ошибки студентов (предупредить заранее)

| Ошибка | Последствие | Что требовать |
|---|---|---|
| Повтор при 403/429 без паузы | эскалация до блокировки | `Retry-After`, backoff, снижение скорости |
| Повторы для 400/404 | лишняя нагрузка, шум в логах | повторять только временные ошибки |
| `time.sleep` фиксированной длины как «вежливость» | либо слишком медленно, либо слишком быстро | token bucket + адаптивная задержка |
| Ровные интервалы без джиттера | ровный «машинный» профиль нагрузки | джиттер 20–30% |
| Локальный лимит при нескольких воркерах | суммарная скорость кратно выше заявленной | общий счётчик или один воркер на домен |
| Проверка только кода ответа | тихая блокировка портит данные | маркеры в теле + smoke-check + сравнение с историей |
| Логи в виде текста | метрики невозможно посчитать | JSON-строки с полями |
| Нет порогов и оповещений | поломка обнаруживается через недели | отчёт о прогоне с порогами |
| «Добавим прокси и капча-солвер» | правовые риски, а не решение | API, sitemap, инкрементальность, запрос доступа |
| Подмена `User-Agent` под браузер | непрозрачность, невозможность связаться | честная строка с контактом |